# Generated by Django 4.2.6 on 2023-10-23 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='price_range',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gift.pricerange'),
            preserve_default=False,
        ),
    ]
