# Generated by Django 4.2.6 on 2023-10-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0002_gift_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
