# Generated by Django 4.2.6 on 2023-10-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0003_gift_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='sha',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
