# Generated by Django 4.2.6 on 2023-10-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0004_gift_sha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='sha',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
