# Generated by Django 4.2.6 on 2023-12-09 15:15

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('wiki_tries', models.PositiveSmallIntegerField(default=0)),
                ('event_slug', models.SlugField(max_length=240)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_page_id', models.PositiveIntegerField()),
                ('wiki_title', models.CharField(blank=True, max_length=240, null=True)),
                ('wiki_description', models.CharField(blank=True, max_length=120, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=240, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('soundcloud', models.URLField(blank=True, null=True)),
                ('spotify', models.URLField(blank=True, null=True)),
                ('appleMusic', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(blank=True, max_length=240, null=True)),
                ('description', models.CharField(blank=True, max_length=960, null=True)),
                ('type', models.CharField(blank=True, max_length=240, null=True)),
                ('location_artist_slug', models.SlugField(max_length=240)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('address', models.TextField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('place_id', models.CharField(max_length=50)),
                ('wiki_tries', models.PositiveSmallIntegerField(default=0)),
                ('event_slug', models.SlugField(max_length=240)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('metadata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.metadata')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('description', models.TextField(default='')),
                ('image', models.URLField()),
                ('url', models.URLField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('provider', models.CharField(max_length=240)),
                ('venue', models.CharField(max_length=240)),
                ('address', models.CharField(default='', max_length=240)),
                ('city', models.CharField(max_length=240)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('gmaps_tries', models.PositiveSmallIntegerField(default=0)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('artists', models.ManyToManyField(blank=True, to='event.artist')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.location')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.metadata'),
        ),
    ]
