# Generated by Django 4.2.6 on 2023-12-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='meta_tries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
