# Generated by Django 4.2.6 on 2023-12-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='event_slug',
        ),
        migrations.RemoveField(
            model_name='location',
            name='event_slug',
        ),
    ]
