# Generated by Django 4.2.6 on 2024-03-25 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('image', models.URLField(blank=True, default='', max_length=420)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.artist')),
                ('genres', models.ManyToManyField(blank=True, to='event.genre')),
            ],
        ),
    ]
