# Generated by Django 4.2.6 on 2023-11-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmapslocation',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='gmapslocation',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='gmapslocation',
            name='place_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
