# Generated by Django 4.2.6 on 2023-12-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
