# Generated by Django 4.2.6 on 2023-11-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
