# Generated by Django 4.2.6 on 2023-11-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
