# Generated by Django 4.2.6 on 2023-11-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_gmapslocation_lat_alter_gmapslocation_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmapslocation',
            name='place_id',
            field=models.CharField(max_length=50),
        ),
    ]
