# Generated by Django 4.2.6 on 2024-01-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_artist_metadata_alter_artist_spotify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotify',
            name='name',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
    ]
