# Generated by Django 4.2.6 on 2023-12-09 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_artist_event_slug_remove_location_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.metadata'),
        ),
    ]
