# Generated by Django 4.2.6 on 2024-02-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_location_provider_alter_artist_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
