# Generated by Django 4.2.6 on 2023-12-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='full_name',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
    ]
