# Generated by Django 4.2.6 on 2024-03-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_musico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musico',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musico',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='event.genre'),
        ),
        migrations.AlterField(
            model_name='musico',
            name='image',
            field=models.URLField(blank=True, default='', max_length=420, null=True),
        ),
        migrations.AlterField(
            model_name='musico',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
