# Generated by Django 4.2.6 on 2023-12-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_location_meta_tries'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='type',
            field=models.CharField(choices=[('ARTIST', 'ARTIST'), ('LOCATION', 'LOCATION')], default='LOCATION', max_length=24),
            preserve_default=False,
        ),
    ]
