# Generated by Django 4.2.6 on 2023-12-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_genre_created_genre_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotify',
            name='image',
            field=models.URLField(blank=True, default='', max_length=240),
        ),
    ]
