# Generated by Django 4.2.6 on 2024-03-25 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_musico_followers_alter_musico_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musico',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musico',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
