# Generated by Django 4.2.6 on 2023-11-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_gmapslocation_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmapslocation',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='gmapslocation',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True),
        ),
    ]
