# Generated by Django 4.2.6 on 2024-01-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_spotify_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='artist_tries',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gmaps_tries',
        ),
        migrations.RemoveField(
            model_name='location',
            name='meta_tries',
        ),
        migrations.RemoveField(
            model_name='spotify',
            name='tries',
        ),
    ]
