# Generated by Django 4.2.6 on 2023-11-12 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_gmapslocation_lat_alter_gmapslocation_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='gmaps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.gmapslocation'),
        ),
    ]
