# Generated by Django 4.2.6 on 2024-02-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_metadata_bandcamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='bandcamp',
            new_name='bandCamp',
        ),
    ]
