# Generated by Django 4.2.6 on 2024-03-25 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_musico_created_musico_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musico',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.artist'),
        ),
    ]
