# Generated by Django 4.2.6 on 2023-12-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_spotify_created_spotify_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(max_length=420),
        ),
    ]
