# Generated by Django 4.2.6 on 2024-02-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_rename_bandcamp_metadata_bandcamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='bandCamp',
            new_name='band_camp',
        ),
        migrations.AddField(
            model_name='metadata',
            name='link_tree',
            field=models.URLField(blank=True, default=''),
        ),
    ]
