# Generated by Django 4.2.6 on 2024-01-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_location_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
