# Generated by Django 4.2.6 on 2024-01-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_location_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, to='event.genre'),
        ),
    ]
