# Generated by Django 4.2.6 on 2024-02-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_location_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
