# Generated by Django 4.2.6 on 2024-02-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_rename_bandcamp_metadata_band_camp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
