# Generated by Django 4.2.6 on 2024-03-28 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_twitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitter',
            name='description',
        ),
    ]
