# Generated by Django 4.2.6 on 2024-03-02 00:35

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_artist_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='name', unique=True),
        ),
    ]
