# Generated by Django 4.2.6 on 2023-12-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_event_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='image',
            field=models.URLField(blank=True, default='', max_length=420),
        ),
    ]
