# Generated by Django 4.2.6 on 2024-02-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_location_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
