# Generated by Django 4.2.6 on 2024-03-03 00:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_artist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='name'),
        ),
    ]
