# Generated by Django 4.2.6 on 2024-04-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_twitter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
