# Generated by Django 4.2.6 on 2024-02-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_location_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='slug_venue',
        ),
        migrations.AddField(
            model_name='location',
            name='slug_venue',
            field=models.ManyToManyField(blank=True, to='event.slug'),
        ),
    ]
