# Generated by Django 4.2.6 on 2024-02-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_slug_remove_location_slug_venue_location_slug_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='buyUrl',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
