# Generated by Django 4.2.6 on 2023-12-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_artist_remove_event_name_event_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='wiki_tries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
