# Generated by Django 4.2.6 on 2024-02-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_event_buyurl_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile',
            field=models.URLField(blank=True, default=''),
        ),
    ]
