# Generated by Django 4.2.6 on 2023-12-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_artist_wiki_tries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='wiki_description',
            field=models.CharField(blank=True, max_length=480, null=True),
        ),
    ]
