# Generated by Django 4.2.6 on 2023-12-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_artist_wiki_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.CharField(blank=True, max_length=480, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='wiki_description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
