# Generated by Django 4.2.6 on 2024-12-15 20:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_location_website_alter_metadata_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, max_length=240, populate_from='name'),
        ),
    ]
