# Generated by Django 4.2.6 on 2023-12-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_artist_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.CharField(blank=True, max_length=960, null=True),
        ),
    ]
