# Generated by Django 4.2.6 on 2023-12-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_alter_artist_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_page_id', models.PositiveSmallIntegerField()),
                ('wiki_title', models.CharField(blank=True, max_length=240, null=True)),
                ('wiki_description', models.CharField(blank=True, max_length=120, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('soundcloud', models.URLField(blank=True, null=True)),
                ('spotify', models.URLField(blank=True, null=True)),
                ('appleMusic', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(blank=True, max_length=240, null=True)),
                ('description', models.CharField(blank=True, max_length=960, null=True)),
                ('type', models.CharField(blank=True, max_length=240, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='appleMusic',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='soundcloud',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='spotify',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='title',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='type',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='website',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='wiki_description',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='wiki_page_id',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='wiki_title',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='youtube',
        ),
        migrations.AddField(
            model_name='location',
            name='wiki_tries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='metadata',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event.metadata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='metadata',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event.metadata'),
            preserve_default=False,
        ),
    ]
