# Generated by Django 4.2.6 on 2023-12-02 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_metadata_remove_artist_applemusic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.metadata'),
        ),
        migrations.AlterField(
            model_name='location',
            name='metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.metadata'),
        ),
    ]
