# Generated by Django 4.2.6 on 2023-12-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_alter_artist_metadata_alter_location_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='wiki_page_id',
            field=models.PositiveIntegerField(),
        ),
    ]
