# Generated by Django 4.2.6 on 2023-11-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('name', models.CharField(max_length=240)),
                ('photo_reference', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200, null=True)),
                ('place_id', models.CharField(max_length=240, unique=True)),
                ('price_level', models.PositiveSmallIntegerField(null=True)),
                ('rating', models.FloatField()),
                ('types', models.CharField(max_length=240)),
                ('user_ratings_total', models.PositiveSmallIntegerField()),
                ('vicinity', models.CharField(max_length=240)),
                ('website', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
