# Generated by Django 4.2.6 on 2023-12-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('name', models.CharField(max_length=240)),
                ('photo_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('place_id', models.CharField(max_length=240)),
                ('price_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('types', models.CharField(max_length=240)),
                ('user_ratings_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vicinity', models.CharField(blank=True, max_length=240, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('permanently_closed', models.BooleanField(default=False)),
                ('gmaps_tries', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
