# Generated by Django 4.2.6 on 2023-11-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_alter_place_image_alter_place_photo_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='permanently_closed',
            field=models.BooleanField(default=False),
        ),
    ]
