# Generated by Django 4.2.6 on 2023-11-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_place_permanently_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='vicinity',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
