# Generated by Django 4.2.6 on 2023-11-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_alter_place_vicinity'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='gmaps_tries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
